# https://dart.dev/guides/language/analysis-options
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - .dart_tool/**
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: true
    cancel_subscriptions: true
    close_sinks: true
    unawaited_futures: true
